In [1]:
import os
import cv2
import time
from tqdm import tqdm
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Conv2D, Dense, MaxPooling2D, Flatten, Activation, Dropout

In [4]:
img_size = 100
datadir = r'C:\Users\hamim\Desktop\assignment\archive\Dataset'
CATEGORIES = os.listdir(datadir)
print(CATEGORIES)

['without_mask', 'with_mask']


In [5]:
# Define two empty list for contain image data
x, y = [], []
   
def PreProcess():
    for category in CATEGORIES:
        path = os.path.join(datadir, category)
        classIndex = CATEGORIES.index(category)
        print(path)
        for imgs in tqdm(os.listdir(path)):
            img_arr = cv2.imread(os.path.join(path, imgs))
            
            # resize the image
            resized_array = cv2.resize(img_arr, (img_size, img_size))
            cv2.imshow("images", resized_array)
            cv2.waitKey(1)
            resized_array = resized_array/255.0
            x.append(resized_array)
            y.append(classIndex)
            
PreProcess()
cv2.destroyAllWindows()

C:\Users\hamim\Desktop\assignment\archive\Dataset\without_mask


100%|██████████| 2994/2994 [00:49<00:00, 60.46it/s]


C:\Users\hamim\Desktop\assignment\archive\Dataset\with_mask


100%|██████████| 2994/2994 [00:50<00:00, 58.79it/s]


In [6]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [7]:
X_train = np.array(X_train).reshape(-1, img_size, img_size, 3)
y_train = np.array(y_train)
X_test = np.array(X_test).reshape(-1, img_size, img_size, 3)
y_test = np.array(y_test)

In [8]:
batch_size = 32
epochs = 10

In [9]:
model = Sequential()

model.add(Conv2D(64,(3, 3), input_shape=(img_size, img_size, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(Dropout(0.25))

model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(100, activation='relu'))
model.add(Dense(16, activation='relu'))


model.add(Dense(len(CATEGORIES)))
model.add(Activation('softmax'))

# compile the model

model.compile(optimizer='adam', loss = 'sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 98, 98, 64)        1792      
                                                                 
 activation (Activation)     (None, 98, 98, 64)        0         
                                                                 
 max_pooling2d (MaxPooling2D  (None, 49, 49, 64)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 47, 47, 256)       147712    
                                                                 
 activation_1 (Activation)   (None, 47, 47, 256)       0         
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 23, 23, 256)      0         
 2D)                                                    

In [10]:
t1 = time.time()

model.fit(X_train, y_train, batch_size = batch_size, epochs=epochs, validation_split=0.3, verbose = 1)
model.save('{}.h5'.format("model"))

t2 = time.time()
print('Time taken: ',t2-t1)

Epoch 1/10
105/105 [==============================] - 137s 1s/step - loss: 0.3071 - accuracy: 0.8700 - val_loss: 0.1655 - val_accuracy: 0.9499
Epoch 2/10
105/105 [==============================] - 124s 1s/step - loss: 0.1620 - accuracy: 0.9466 - val_loss: 0.0996 - val_accuracy: 0.9680
Epoch 3/10
105/105 [==============================] - 122s 1s/step - loss: 0.1343 - accuracy: 0.9585 - val_loss: 0.1275 - val_accuracy: 0.9603
Epoch 4/10
105/105 [==============================] - 144s 1s/step - loss: 0.1244 - accuracy: 0.9597 - val_loss: 0.1502 - val_accuracy: 0.9485
Epoch 5/10
105/105 [==============================] - 138s 1s/step - loss: 0.1125 - accuracy: 0.9654 - val_loss: 0.1260 - val_accuracy: 0.9645
Epoch 6/10
105/105 [==============================] - 131s 1s/step - loss: 0.1061 - accuracy: 0.9660 - val_loss: 0.1013 - val_accuracy: 0.9736
Epoch 7/10
105/105 [==============================] - 119s 1s/step - loss: 0.1108 - accuracy: 0.9684 - val_loss: 0.1029 - val_accuracy: 0.9701

In [11]:
validation_loss, validation_accuracy = model.evaluate(X_test, y_test)

38/38 [==============================] - 12s 298ms/step - loss: 0.1273 - accuracy: 0.9558


In [6]:
import cv2
import mediapipe as mp
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model

# Load the model
model = load_model('model.h5')

# Define mediapipe Face detector

face_detection = mp.solutions.face_detection.FaceDetection()

# Detection function



def get_detection(frame):


    height, width, channel = frame.shape

    # Convert frame BGR to RGB colorspace

    imgRGB = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    # Detect results from the frame
    
    result = face_detection.process(imgRGB)


    try:
        for count, detection in enumerate(result.detections):

            # print(detection)

        
            # Extract bounding box information 
            
            box = detection.location_data.relative_bounding_box

            x, y, w, h = int(box.xmin*width), int(box.ymin * height), int(box.width*width), int(box.height*height)
            
    # If detection is not available then pass 
    except:
        pass

    return x, y, w, h

CATEGORIES = ['no_mask','mask' ]
cap = cv2.VideoCapture(0)
while True:
    _, frame = cap.read()
    img = frame.copy()
    try:
        x, y, w, h = get_detection(frame)
        
        crop_img = img[y:y+h, x:x+w]
        
        crop_img = cv2.resize(crop_img, (100, 100))
        
        crop_img = np.expand_dims(crop_img, axis=0)
        
        # get the prediction from the model.
        prediction = model.predict(crop_img)
        print(prediction)
        index = np.argmax(prediction)
        res = CATEGORIES[index]
        if index == 0:
            color = (0, 0, 255)
        else:
            color = (0, 255, 0)
        cv2.rectangle(frame, (x, y), (x+w, y+h), color, 2)
        cv2.putText(frame, res, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX,
                                 0.8, color, 2, cv2.LINE_AA)

    except:
        pass
    
    cv2.imshow("frame", frame)
    if cv2.waitKey(1) == ord('o'):
        break
    
cap.release()
cv2.destroyAllWindows()

1/1 [==============================] - 0s 189ms/step
[[4.9580898e-08 1.0000000e+00]]
1/1 [==============================] - 0s 57ms/step
[[1. 0.]]
1/1 [==============================] - 0s 63ms/step
[[1. 0.]]
1/1 [==============================] - 0s 49ms/step
[[1. 0.]]
1/1 [==============================] - 0s 64ms/step
[[1. 0.]]
1/1 [==============================] - 0s 41ms/step
[[1. 0.]]
1/1 [==============================] - 0s 55ms/step
[[1. 0.]]
1/1 [==============================] - 0s 65ms/step
[[1. 0.]]
1/1 [==============================] - 0s 59ms/step
[[0. 1.]]
1/1 [==============================] - 0s 46ms/step
[[0. 1.]]
1/1 [==============================] - 0s 57ms/step
[[0. 1.]]
1/1 [==============================] - 0s 46ms/step
[[0. 1.]]
1/1 [==============================] - 0s 49ms/step
[[0. 1.]]
1/1 [==============================] - 0s 65ms/step
[[0.9615176  0.03848249]]
1/1 [==============================] - 0s 58ms/step
[[0.99814665 0.00185331]]
1/1 [==========